### PR TITLE
Feat geometries

### PR DESCRIPTION
**Pull request by samuel-girard**
Implements Multi-polygon geometry.
I also refactored geometries (now isolated in their directory).

Point coordinates can now be passed as property of the GeometryPointComponent (`<aol-geometry-point [coordinates]="[5, 45]" [srid]="'EPSG:4326'"></aol-geometry-point>`) instead of in a child component.
The coordinates reprojection feature still works thanks to the srid property.

### CODE REVIEW

**Comment by quentin-ol** [comment]
Hey,

I'm not entirely sure about the implications of this change, i.e. from aol-coordinates objects to properties of geometries. Let's make a hangouts/phone call to discuss this. Anyways, In the meantime, there is still a lot of duplicate code in the geometries. Perhaps we should make a GeometryComponent and push all of the redundant code in there. Opinions ?

**Comment by davinkevin** [comment]
+1 with @quentin-ol to talk about this one

**Comment by samuel-girard** [comment]
Hello,

Ok for a call to talk about it. I'll see with @davinkevin how you used to contact each other.

**Comment by samuel-girard** [comment]
Hello,

We found a better solution to bring multi-geometries to ngx-openlayers without changing the previous coordinates behaviour:

- MultiPoint, MultiLinestring, MultiPolygon support
- Geometries are moved to their own subdirectory
- coordinates reprojection
- aol-coordinates behaviour is not changed as I stated earlier, but it works like before

@quentin-ol , @davinkevin : let me know if you have any remarks about it.

**Pull request closed without merging**
