### PR TITLE
feat(view): set animation on zoom changes

### PR DESCRIPTION
**Pull request by samuel-girard**
Hello @quentin-ol 

I added a new input value on the view component to animate the zoom.
Unlike other inputs on the View component, this one doesn't follow OpenLayers View API, but I cannot think of a better way.

Thanks

### CODE REVIEW

**Comment by quentin-ol** [comment]
Hey! Happy new year, I'm back from holidays!

Thanks for the PR! Regarding the way to implement this, I'm not confortable having 2 zoom property for the same instance (should we allow using the two at the same time, should we sync the values, etc). Is there any reason why we wouldn't use a boolean property to enable/disable the animation?
Using it would be be achieved in the following way: 
```
<aol-view [zoom]="zoom" [zoom-animation]="True">
```

**Comment by samuel-girard** [comment]
Hello @quentin-ol 
Welcome back from holidays and happy new year too!

In fact, this is the way it is already working (it was not clear in my first post):
```html
<aol-view [zoom]="zoom" [animatedZoom]="true">
```
Perhaps, I should change the property name to `zoomAnimation` as you suggest to make it more clear?

**Comment by quentin-ol** [comment]
well, this goes down to personal/collective preference. Opinions ?

**Comment by samuel-girard** [comment]
I think **zoomAnimation** reflects better the purpose of this property.
I'll make a change in this way.

**Comment by quentin-ol** [comment]
then let's do it!

**Pull request merged**
