### PR TITLE
feat(source:imagestatic): refresh layer source when url change

### PR DESCRIPTION
**Pull request by clara-belair**
@Neonox31 / @Yakoust 🚀 🐰

### CODE REVIEW

**Comment by Yakoust** [comment]
Maybe we should wait for merge #231 in order to add an example of what happens when url is changed

**Comment by clara-belair** [comment]
> Maybe we should wait for merge #231 in order to add an example of what happens when url is changed

Yes @Yakoust 
@kekel87 / @Neonox31 can you check this please : #231

**Comment by kekel87** [comment]
Done, #231 it's good for me. This one too !

**Comment by clara-belair** [comment]
@Yakoust I have updated the example of image-static

**Comment by Yakoust** [comment]
LGTM :+1:

**Pull request merged**
