### PR TITLE
Add missing API properties for vector layer

### PR DESCRIPTION
**Pull request by HarelM**
Related to #198.

### CODE REVIEW

**Comment by HarelM** [comment]
The lint fails on something I didn't touch... Any comment? I really need this merged and published to npm in order to fix one of the last beta bugs I have:
https://github.com/IsraelHikingMap/Site/issues/876

**Comment by Neonox31** [comment]
@HarelM Sorry, I just fixed the linting problem on `next` branch.

**Comment by Neonox31** [comment]
@Yakoust @davinkevin @kekel87 Could you please take a look ?

**Comment by HarelM** [comment]
Any updates on this? This PR is waiting to be merged for two month now... :-/

**Comment by kekel87** [comment]
Sorry about that, LGTM.

**Pull request merged**
