### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by HarelM**
Related to #189.

### CODE REVIEW

**Comment by davinkevin** [comment]
There is already a website with some example => https://quentin-ol.github.io/ngx-openlayers/
And the source code is in the branch `next` (based upon Angular 6, but was the same in ng5) => https://github.com/quentin-ol/ngx-openlayers/tree/next/src/app

You still think this is useful in the `README.md` too ? 😊

Let me know and I will merge it.

**Comment by Yakoust** [comment]
@Neonox31 @davinkevin do you see anything blocking this PR?

**Comment by davinkevin** [comment]
Ok for me 👍

**Comment by davinkevin** [comment]
BTW, this modification should be reported on the `next` branch too.

**Pull request merged**
