### PR TITLE
chore: update to angular 9

### PR DESCRIPTION
**Pull request by kekel87**
- migrate to angular 9.1
- upgrade demo to openlayer 6.3.1
- fix cyclic dependencies for Raster (change Sources management)
- migrate hammer to use HammerModule (Swipe exemple)
- add umdModuleIds to handle ng-packagr warning
- fix arcgis & tilejson example
- format with prettier
- clean unused dependencies (hammer-timejs & geojson)

@Neonox31 / @Yakoust / @davinkevin 

**Important points** : 
- I am not applying the Ivy migration which adds `@Directive ()` to `LayerComponent`, `SourceComponent` and `SimpleGeometryComponent` because it raise too much problem.

- There is still some non-blocking  warning during lib build (it seems to me that they have been there for a while).
<details>
<summary>Build warning</summary>

```sh
------------------------------------------------------------------------------
Building entry point 'ngx-openlayers'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
WARNING: 'OnInit', 'AfterViewInit', 'SimpleChanges', 'OnChanges' and 'OnDestroy' are imported from external module '@angular/core' but never used
Bundling to FESM5
WARNING: 'OnInit', 'AfterViewInit', 'SimpleChanges', 'OnChanges' and 'OnDestroy' are imported from external module '@angular/core' but never used
Bundling to UMD
Minifying UMD bundle
Writing package metadata
Removing scripts section in package.json as it's considered a potential security vulnerability.
Built ngx-openlayers
```
</details>

- There is a big warning only when serving in Ivy, but the application works. I opened an issue in [angular/angular](https://github.com/angular/angular/issues/35750).
<details>
<summary>Ivy serve warning</summary>

```sh
WARNING in Entry point 'ngx-openlayers' contains deep imports into
  'projets/github/ngx-openlayers/node_modules/ol/View',
  'projets/github/ngx-openlayers/node_modules/ol/Map',
  'projets/github/ngx-openlayers/node_modules/ol/layer',
  'projets/github/ngx-openlayers/node_modules/ol/source',
  'projets/github/ngx-openlayers/node_modules/ol/tilegrid',
  'projets/github/ngx-openlayers/node_modules/ol/tilegrid/TileGrid',
  'projets/github/ngx-openlayers/node_modules/ol/tilegrid/WMTS',
  'projets/github/ngx-openlayers/node_modules/ol/format',
  'projets/github/ngx-openlayers/node_modules/ol/geom',
  'projets/github/ngx-openlayers/node_modules/ol/proj',
  'projets/github/ngx-openlayers/node_modules/ol/style',
  'projets/github/ngx-openlayers/node_modules/ol/control',
  'projets/github/ngx-openlayers/node_modules/ol/control/MousePosition',
  'projets/github/ngx-openlayers/node_modules/ol/interaction',
  'projets/github/ngx-openlayers/node_modules/ol/geom/SimpleGeometry',
  'projets/github/ngx-openlayers/node_modules/ol/format/Feature',
  'projets/github/ngx-openlayers/node_modules/ol/MapBrowserEvent',
  'projets/github/ngx-openlayers/node_modules/ol/MapEvent',
  'projets/github/ngx-openlayers/node_modules/ol/Object',
  'projets/github/ngx-openlayers/node_modules/ol/render/Event',
  'projets/github/ngx-openlayers/node_modules/ol/style/Style',
  'projets/github/ngx-openlayers/node_modules/ol/events',
  'projets/github/ngx-openlayers/node_modules/ol/extent',
  'projets/github/ngx-openlayers/node_modules/ol/source/Vector',
  'projets/github/ngx-openlayers/node_modules/ol/coordinate',
  'projets/github/ngx-openlayers/node_modules/ol/layer/VectorTile',
  'projets/github/ngx-openlayers/node_modules/ol/source/Source',
  'projets/github/ngx-openlayers/node_modules/ol/source/Tile',
  'projets/github/ngx-openlayers/node_modules/ol/Tile',
  'projets/github/ngx-openlayers/node_modules/ol/size',
  'projets/github/ngx-openlayers/node_modules/ol/Image',
  'projets/github/ngx-openlayers/node_modules/ol/source/Raster',
  'projets/github/ngx-openlayers/node_modules/ol/OverlayPositioning',
  'projets/github/ngx-openlayers/node_modules/ol/color',
  'projets/github/ngx-openlayers/node_modules/ol/style/IconAnchorUnits',
  'projets/github/ngx-openlayers/node_modules/ol/style/IconOrigin',
  'projets/github/ngx-openlayers/node_modules/ol/colorlike',
  'projets/github/ngx-openlayers/node_modules/ol/control/Attribution',
  'projets/github/ngx-openlayers/node_modules/ol/control/Rotate',
  'projets/github/ngx-openlayers/node_modules/ol/control/Zoom',
  'projets/github/ngx-openlayers/node_modules/ol/geom/GeometryType',
  'projets/github/ngx-openlayers/node_modules/ol/events/condition',
  'projets/github/ngx-openlayers/node_modules/ol/interaction/DragBox',
  'projets/github/ngx-openlayers/node_modules/ol/Kinetic',
  'projets/github/ngx-openlayers/node_modules/ol/interaction/Draw',
  'projets/github/ngx-openlayers/node_modules/ol/interaction/Select',
  'projets/github/ngx-openlayers/node_modules/ol/interaction/Translate'.
This is probably not a problem, but may cause the compilation of entry points to be out of order.
```
</details>

### CODE REVIEW

**Comment by Helveg** [comment]
@kekel87 Can you also look into the 25 vulnerabilities (4 low, 7 moderate, 13 high, 1 critical) reported by NPM?

**Comment by kekel87** [comment]
> @kekel87 Can you also look into the 25 vulnerabilities (4 low, 7 moderate, 13 high, 1 critical) reported by NPM? Seems like it could fit in nicely with this PR since you're updating dependencies anyway.

I update angular & co. Many high vulnerabilities came from `standard-version`, i updated it. The latest high 
 vulnerabilities come from protractor but it is dictated by angular.

**Comment by kekel87** [comment]
About warning only when serving in Ivy, I opened an issue in angular/angular.

**Comment by kekel87** [comment]
I also update openlayer to 6.3.1 (avoid 6.3.0 du to typings issues)/

**Comment by kekel87** [comment]
I update to [@angular@9.1.1](https://github.com/angular/angular/blob/master/CHANGELOG.md#911-2020-04-07) and `deep imports` message is gone. ✌️

**Comment by gongAll** [comment]
Will this be merged any time soon? @quentin-ol

**Comment by Neonox31** [comment]
@kekel87 Many thanks for the P.R and nice work 💪
@Yakoust I merged because the review take too much time and if there something to fixed we will do new releases.

@all I will create a new release on next dist tag.

**Comment by gongAll** [comment]
@Neonox31 the "next" tag version is still "1.0.0-next.13" in [npm site](https://www.npmjs.com/package/ngx-openlayers).

**Comment by Neonox31** [comment]
> @Neonox31 the "next" tag version is still "1.0.0-next.13" in [npm site](https://www.npmjs.com/package/ngx-openlayers).

OK thanks, we're investigating the problem with @kekel87

**Comment by Neonox31** [comment]
@gongAll We have just published the `1.0.0-next.15` tag which resolves the non published dist-tags.

**Pull request merged**
