### PR TITLE
feat(Layer): add pre and post compose inputs and change behavior for …

### PR DESCRIPTION
**Pull request by aymeric-duchein**
…all Layers

@davinkevin @Neonox31 @Yakoust

### CODE REVIEW

**Comment by davinkevin** [comment]
Any update @quentin-ol about this one ?

Thanks

**Comment by quentin-ol** [comment]
sorry, needed a reminder ;) Thanks!

**Comment by quentin-ol** [comment]
should I wait for the the other PR to push a new version on npm?

**Comment by davinkevin** [comment]
Thanks you 👍

**Comment by aymeric-duchein** [comment]
Whne do you think the other PR (#129) will be merged? If it's today or tomorrow we can wait, if not it'll be very nice of you to publish this to npm. Thx

**Comment by quentin-ol** [comment]
done.

**Pull request merged**
