### PR TITLE
chore(ci): add auto publish stage

### PR DESCRIPTION
**Pull request by Neonox31**
Add a NPM auto publish stage in .travis.yml file

Now, you could use this following command to release a new version : `npm run release && git push && git push --tags`
The commit and tag are automatically created and after push travis auto deploys newly created NPM package according to tag.

Don't forget to add `NPM_TOKEN` and `NPM_EMAIL` travis variables.

### CODE REVIEW

**Comment by davinkevin** [comment]
Very helpful, let us know if you're interested on things like this in future... 
We ❤️ to automate 😉

**Comment by quentin-ol** [comment]
Yes, this is neat! Just give a bit more time to set the travis tokens before I merge this (got a ton of urgents matters to deal with)!

**Comment by davinkevin** [comment]
If you need help for doing this (to save time or else), don't hesitate to ask ourselves ( /cc @Neonox31 )

**Comment by quentin-ol** [comment]
online!

**Pull request merged**
