### PR TITLE
feat(source:wmts): refresh layer source when url change

### PR DESCRIPTION
**Pull request by Yakoust**

### CODE REVIEW

**Comment by quentin-ol** [comment]
Thanks for the PR! In the code comments, you state that it's a work-around. Is there a bug in OpenLayers regarding this or is it a binding issue ? I've had similar issues that can be summed-up like this:
- ol.thing is initialized with parameters ( possibly of primitive types, i.e. `int`)
- the user provides a new`value` i.e. input is provided with a new `object/parameter`
- OpenLayers does not act upon the change because the initial value has not been changed, the controller just got a new `object` altogether that needs to be explicitly passed to `ol.thing` to be acknowledged.
 If it falls in this description, let's remove the `work-around` comment. 

In any case, thanks a lot for the PR! This will be merged, with or without the comment.

**Comment by Yakoust** [comment]
Hello,

You're right. I said that because, for me, it's not a natural way to re-set an instance just for a property update.
I am agree that it is an OpenLayers normal use case.
We can remove this comment

**Comment by quentin-ol** [comment]
Ok, thanks for the explanation. Let's do it without the "work-around" comment as it's basically the only way to do it. Thanks again for the PR.

**Comment by Yakoust** [comment]
Done!

**Comment by quentin-ol** [comment]
great! Thanks @Yakoust !

**Comment by quentin-ol** [comment]
published, version 0.6.10 is live on npm.

**Pull request merged**
