### PR TITLE
chore(build): use angular package builder

### LINKED ISSUE #149: chore(build): move to angular-package-builder
Hi, 

We would like to propose a new way to build the application around the project of 
`dominique-mueller` named `angular-package-builder` (https://github.com/dominique-mueller/angular-package-builder). 

This `builder` allows to provide the lib as `ESM2015`, `ESM5`, `UMD` module.  We have tested it with `ngx-openlayers` and this is working well (minus some adjustment on some components).

If it's ok for you, we can do this in a pull request. 

/cc @Neonox31 @Yakoust @yann29 @aymeric-duchein

### PR DESCRIPTION
**Pull request by davinkevin**
This PR integrate the modification required by the `angular-package-builder`.

/cc @Neonox31 @Yakoust @Yann29

Closes #149

### CODE REVIEW

**Comment by davinkevin** [comment]
@quentin-ol Is it ok for you ?

**Comment by quentin-ol** [comment]
Hey @davinkevin, just a quick remark: I see that the PR contains both the package builder changes and others: (feats full-screen, rotate, zoom-slider). Is it a mix-up in commits and branches or is there a reason ? Otherwise, yes. I agree with the package builder changes.

**Comment by davinkevin** [comment]
It's normal (I'v add information inside the commit message of each one).

Those modification / improvement are mainly driven by the compiler errors thrown during build process. The package builder is more strict thanks now.

**Comment by davinkevin** [comment]
Due to the last release of `@angular/cli`, which will support library building, I prefer to close this PR. 
> https://github.com/angular/angular-cli/releases/tag/v6.0.0-rc.2

**Pull request closed without merging**
